TipddyMasleadsBundle_login:
    resource: "@TipddyMasleadsBundle/Resources/config/routing/login.yml"
    prefix: /
    
TipddyMasleadsBundle_dashboard:
    resource: "@TipddyMasleadsBundle/Resources/config/routing/panel.yml"
    prefix: /dashboard     

TipddyMasleadsBundle_campaign:
    resource: "@TipddyMasleadsBundle/Resources/config/routing/campana.yml"
    prefix: /campaign    

TipddyMasleadsBundle_user:
    resource: "@TipddyMasleadsBundle/Resources/config/routing/usuario.yml"
    prefix: /user    

TipddyMasleadsBundle_company:
    resource: "@TipddyMasleadsBundle/Resources/config/routing/organizacion.yml"
    prefix: /company       


TipddyMasleadsBundle_comment:
    resource: "@TipddyMasleadsBundle/Resources/config/routing/comentario.yml"
    prefix: /comment     
    
TipddyMasleadsBundle_ajax:
    resource: "@TipddyMasleadsBundle/Resources/config/routing/ajax.yml"
    prefix: /ajax   