parameters:
#    tipddy_api.example.class: Tipddy\ApiBundle\Example

services:
#    tipddy_api.example:
#        class: %tipddy_api.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
