security:
    firewalls:
       administrator:
             pattern: ^/
             anonymous: ~
             form_login: 
                login_path: login
                check_path: login_check
             
    access_control:
#       - { path: ^/panel , roles: [ROLE_TIPDDY, ROLE_ADMIN, ROLE_GERENTE, ROLE_VENDEDOR] } 
#       - { path: ^/campana , roles: [ROLE_TIPDDY, ROLE_ADMIN, ROLE_GERENTE, ROLE_VENDEDOR] }        
#       - { path: ^/usuario , roles: [ROLE_TIPDDY, ROLE_ADMIN] }
#       - { path: ^/organizacion , roles: ROLE_TIPDDY }
#       - { path: ^/comentario , roles: ROLE_TIPDDY }           
        
    providers:
       usuarios:
          entity: { class: Tipddy\MasleadsBundle\Entity\Usuarios, property: login }
          
          
    encoders:
       Tipddy\MasleadsBundle\Entity\Usuarios: plaintext
   #   Tipddy\MasleadsBundle\Entity\Usuarios: { algorithm: sha512, iterations: 10} 