security:
    firewalls:
       administrator:
             pattern: ^/
             anonymous: ~
             form_login: 
                login_path: login
                check_path: login_check
                always_use_default_target_path: true
                default_target_path: /dashboard
             logout:
                path: /logout
                target: / 
             
    access_control:
       - { path: ^/dashboard , roles: [ROLE_TIPDDY, ROLE_ADMIN, ROLE_GERENTE, ROLE_VENDEDOR] } 
       - { path: ^/campaign , roles: [ROLE_TIPDDY, ROLE_ADMIN, ROLE_GERENTE, ROLE_VENDEDOR] }        
       - { path: ^/user , roles: [ROLE_TIPDDY, ROLE_ADMIN] }
       - { path: ^/company , roles: ROLE_TIPDDY }
       - { path: ^/comment , roles: ROLE_TIPDDY }           
              
    encoders:
       Tipddy\MasleadsBundle\Entity\Usuarios:
           algorithm: sha512
           iterations: 1 
       
    providers:
       usuarios:
          entity: { class: Tipddy\MasleadsBundle\Entity\Usuarios, property: login }
          
