<?php

namespace Tipddy\MasleadsBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * CampanasRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CampanasRepository extends EntityRepository
{
    public function buildQueryOrmAdapter($idOrganizacion)
    {
        $em = $this->getEntityManager();
          
        $query = $em->createQueryBuilder()
                        ->select('c')
                        ->from('TipddyMasleadsBundle:Campanas', 'c')
                        ->where('c.organizacion = :idOrganizacion')
                        ->orderBy('c.id', 'DESC')
                        ->setParameter('idOrganizacion', $idOrganizacion);
       
         return $query;
       
    }


}