<?php

namespace Tipddy\MasleadsBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * EnviosInformacionRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class EnviosInformacionRepository extends EntityRepository
{
    public function buildQueryOrmAdapter()
    {
        $em = $this->getEntityManager();
          
        $query = $em->createQueryBuilder()
                        ->select('e')
                        ->from('TipddyMasleadsBundle:EnviosInformacion', 'e')
                        ->orderBy('e.id', 'DESC'); 
       
         return $query;
       
    }

   
}