<?php

namespace Application\Migrations;

use Doctrine\DBAL\Migrations\AbstractMigration,
    Doctrine\DBAL\Schema\Schema;

/**
 * Auto-generated Migration: Please modify to your need!
 */
class Version20120706164223 extends AbstractMigration
{
    public function up(Schema $schema)
    {
        // this up() migration is autogenerated, please modify it to your needs
        $this->abortIf($this->connection->getDatabasePlatform()->getName() != "mysql");
        
        $this->addSql("CREATE TABLE paises (id BIGINT AUTO_INCREMENT NOT NULL, nombre VARCHAR(100) NOT NULL, isonum INT NOT NULL, iso2 VARCHAR(2) NOT NULL, iso3 VARCHAR(3) NOT NULL, PRIMARY KEY(id)) ENGINE = InnoDB");
        $this->addSql("ALTER TABLE campanas CHANGE periodo_prueba periodo_prueba TINYINT(1) NOT NULL");
        $this->addSql("ALTER TABLE comunas DROP FOREIGN KEY comunas_ibfk_2");
        $this->addSql("ALTER TABLE comunas DROP FOREIGN KEY comunas_ibfk_1");
        $this->addSql("ALTER TABLE comunas ADD CONSTRAINT FK_14704B9198260155 FOREIGN KEY (region_id) REFERENCES regiones(id)");
        $this->addSql("ALTER TABLE comunas ADD CONSTRAINT FK_14704B914E7121AF FOREIGN KEY (provincia_id) REFERENCES provincias(id)");
    }

    public function down(Schema $schema)
    {
        // this down() migration is autogenerated, please modify it to your needs
        $this->abortIf($this->connection->getDatabasePlatform()->getName() != "mysql");
        
        $this->addSql("DROP TABLE paises");
        $this->addSql("ALTER TABLE campanas CHANGE periodo_prueba periodo_prueba TINYINT(1) DEFAULT '1' NOT NULL");
        $this->addSql("ALTER TABLE comunas DROP FOREIGN KEY FK_14704B9198260155");
        $this->addSql("ALTER TABLE comunas DROP FOREIGN KEY FK_14704B914E7121AF");
        $this->addSql("ALTER TABLE comunas ADD CONSTRAINT comunas_ibfk_2 FOREIGN KEY (provincia_id) REFERENCES provincias(id) ON UPDATE CASCADE ON DELETE CASCADE");
        $this->addSql("ALTER TABLE comunas ADD CONSTRAINT comunas_ibfk_1 FOREIGN KEY (region_id) REFERENCES regiones(id) ON UPDATE CASCADE ON DELETE CASCADE");
    }
}
