<?php

namespace Application\Migrations;

use Doctrine\DBAL\Migrations\AbstractMigration,
    Doctrine\DBAL\Schema\Schema;

/**
 * Auto-generated Migration: Please modify to your need!
 */
class Version20120708002425 extends AbstractMigration
{
    public function up(Schema $schema)
    {
        // this up() migration is autogenerated, please modify it to your needs
        $this->abortIf($this->connection->getDatabasePlatform()->getName() != "mysql");
        
        $this->addSql("ALTER TABLE organizaciones CHANGE pais_id pais_id BIGINT NOT NULL");
        $this->addSql("ALTER TABLE tipos_usuarios ADD nombre VARCHAR(255) NOT NULL");
    }

    public function down(Schema $schema)
    {
        // this down() migration is autogenerated, please modify it to your needs
        $this->abortIf($this->connection->getDatabasePlatform()->getName() != "mysql");
        
        $this->addSql("ALTER TABLE organizaciones CHANGE pais_id pais_id BIGINT DEFAULT NULL");
        $this->addSql("ALTER TABLE tipos_usuarios DROP nombre");
    }
}
