<?php

namespace Application\Migrations;

use Doctrine\DBAL\Migrations\AbstractMigration,
    Doctrine\DBAL\Schema\Schema;

/**
 * Auto-generated Migration: Please modify to your need!
 */
class Version20120706170728 extends AbstractMigration
{
    public function up(Schema $schema)
    {
        // this up() migration is autogenerated, please modify it to your needs
        $this->abortIf($this->connection->getDatabasePlatform()->getName() != "mysql");
        
        $this->addSql("ALTER TABLE organizaciones DROP FOREIGN KEY FK_D9BD584ED39AF213");
        $this->addSql("ALTER TABLE organizaciones DROP FOREIGN KEY FK_D9BD584EF62F176");
        $this->addSql("DROP INDEX IDX_D9BD584EF62F176 ON organizaciones");
        $this->addSql("DROP INDEX IDX_D9BD584ED39AF213 ON organizaciones");
        $this->addSql("ALTER TABLE organizaciones DROP provincia, DROP region");
    }

    public function down(Schema $schema)
    {
        // this down() migration is autogenerated, please modify it to your needs
        $this->abortIf($this->connection->getDatabasePlatform()->getName() != "mysql");
        
        $this->addSql("ALTER TABLE organizaciones ADD provincia BIGINT DEFAULT NULL, ADD region BIGINT DEFAULT NULL");
        $this->addSql("ALTER TABLE organizaciones ADD CONSTRAINT FK_D9BD584ED39AF213 FOREIGN KEY (provincia) REFERENCES provincias(id)");
        $this->addSql("ALTER TABLE organizaciones ADD CONSTRAINT FK_D9BD584EF62F176 FOREIGN KEY (region) REFERENCES regiones(id)");
        $this->addSql("CREATE INDEX IDX_D9BD584EF62F176 ON organizaciones (region)");
        $this->addSql("CREATE INDEX IDX_D9BD584ED39AF213 ON organizaciones (provincia)");
    }
}
