<?php

namespace Application\Migrations;

use Doctrine\DBAL\Migrations\AbstractMigration,
    Doctrine\DBAL\Schema\Schema;

/**
 * Auto-generated Migration: Please modify to your need!
 */
class Version20120706165024 extends AbstractMigration
{
    public function up(Schema $schema)
    {
        // this up() migration is autogenerated, please modify it to your needs
        $this->abortIf($this->connection->getDatabasePlatform()->getName() != "mysql");
        
        $this->addSql("ALTER TABLE organizaciones ADD pais_id BIGINT DEFAULT NULL, DROP pais");
        $this->addSql("ALTER TABLE organizaciones ADD CONSTRAINT FK_D9BD584EC604D5C6 FOREIGN KEY (pais_id) REFERENCES paises(id)");
        $this->addSql("CREATE INDEX IDX_D9BD584EC604D5C6 ON organizaciones (pais_id)");
    }

    public function down(Schema $schema)
    {
        // this down() migration is autogenerated, please modify it to your needs
        $this->abortIf($this->connection->getDatabasePlatform()->getName() != "mysql");
        
        $this->addSql("ALTER TABLE organizaciones DROP FOREIGN KEY FK_D9BD584EC604D5C6");
        $this->addSql("DROP INDEX IDX_D9BD584EC604D5C6 ON organizaciones");
        $this->addSql("ALTER TABLE organizaciones ADD pais VARCHAR(255) NOT NULL, DROP pais_id");
    }
}
