campana:
  pattern: /{page}
  defaults: { _controller: TipddyMasleadsBundle:Campana:index, page: 1 }
  requirements: 
    page: \d+
  
campana_ver:
    pattern:  /{id}/ver
    defaults: { _controller: "TipddyMasleadsBundle:Campana:ver" }

campana_nuevo:
    pattern:  /nuevo
    defaults: { _controller: "TipddyMasleadsBundle:Campana:nuevo" }

campana_crear:
    pattern:  /crear
    defaults: { _controller: "TipddyMasleadsBundle:Campana:crear" }
    requirements: { _method: post }

campana_editar:
    pattern:  /{id}/editar
    defaults: { _controller: "TipddyMasleadsBundle:Campana:editar" }

campana_actualizar:
    pattern:  /{id}/actualizar
    defaults: { _controller: "TipddyMasleadsBundle:Campana:actualizar" }
    requirements: { _method: post }

campana_borrar:
    pattern:  /{id}/borrar
    defaults: { _controller: "TipddyMasleadsBundle:Campana:borrar" }
    requirements: { _method: post }

  