campaign:
    pattern: /{page}
    defaults: { _controller: "TipddyMasleadsBundle:Campana:index", page: 1 }
    requirements: 
        page: \d+
  
campaign_show:
    pattern:  /{id}/show/{page}
    defaults: { _controller: "TipddyMasleadsBundle:Campana:show", page: 1 }
    requirements:
        page: \d+
        id: \d+        
        
campaign_new:
    pattern:  /new
    defaults: { _controller: "TipddyMasleadsBundle:Campana:new" }

campaign_create:
    pattern:  /create
    defaults: { _controller: "TipddyMasleadsBundle:Campana:create" }
    requirements: { _method: post }

campaign_edit:
    pattern:  /{id}/edit/{page}
    defaults: { _controller: "TipddyMasleadsBundle:Campana:edit", page: 1 }
    requirements:
        page: \d+
        id: \d+

campaign_update:
    pattern:  /{id}/update/{page}
    defaults: { _controller: "TipddyMasleadsBundle:Campana:update", page: 1 }
    requirements: 
        _method: post
        id: \d+ 
        page: \d+

campaign_delete:
    pattern:  /{id}/delete/{page}
    defaults: { _controller: "TipddyMasleadsBundle:Campana:delete", page: 1 }
    requirements:
        _method: post
        page: \d+ 

  