comment:
   pattern: /{page}
   defaults: { _controller:"TipddyMasleadsBundle:Comentario:index", page: 1 }
   requirements:
      page: \d+
      
comment_show:
    pattern:  /{id}/show/{page}
    defaults: { _controller: "TipddyMasleadsBundle:Comentario:show", page: 1 }
    requirements:
        page: \d+
        id: \d+

comment_new:
    pattern:  /new
    defaults: { _controller: "TipddyMasleadsBundle:Comentario:new" }

comment_create:
    pattern:  /create
    defaults: { _controller: "TipddyMasleadsBundle:Comentario:create" }
    requirements: { _method: post }

comment_edit:
    pattern:  /{id}/edit/{page}
    defaults: { _controller: "TipddyMasleadsBundle:Comentario:edit", page: 1 }
    requirements:
        id: \d+
        page: \d+

comment_update:
    pattern:  /{id}/update/{page}
    defaults: { _controller: "TipddyMasleadsBundle:Comentario:actualizar", page: 1 }
    requirements:
        _method: post
        id: \d+
        page: \d+

comment_delete:
    pattern:  /{id}/delete/{page}
    defaults: { _controller: "TipddyMasleadsBundle:Comentario:delete", page: 1 }
    requirements: 
        _method: post
        id: \d+
        page: \d+