company:
   pattern: /{page}
   defaults: {_controller:"TipddyMasleadsBundle:Organizacion:index", page: 1}
   requirements:
      page: \d+
   
company_show:
    pattern:  /{id}/show
    defaults: { _controller: "TipddyMasleadsBundle:Organizacion:show" }

company_new:
    pattern:  /new
    defaults: { _controller: "TipddyMasleadsBundle:Organizacion:new" }

company_create:
    pattern:  /create
    defaults: { _controller: "TipddyMasleadsBundle:Organizacion:create" }
    requirements: { _method: post }

company_edit:
    pattern:  /{id}/edit
    defaults: { _controller: "TipddyMasleadsBundle:Organizacion:edit" }

company_update:
    pattern:  /{id}/update
    defaults: { _controller: "TipddyMasleadsBundle:Organizacion:update" }
    requirements: { _method: post }

company_delete:
    pattern:  /{id}/delete
    defaults: { _controller: "TipddyMasleadsBundle:Organizacion:delete" }
    requirements: { _method: post }

  