company:
   pattern: /{page}
   defaults: {_controller:"TipddyMasleadsBundle:Organizacion:index", page: 1}
   requirements:
      page: \d+
   
company_show:
    pattern:  /{id}/show/{page}
    defaults: { _controller: "TipddyMasleadsBundle:Organizacion:show", page: 1 }
    requirements:
        page: \d+

company_new:
    pattern:  /new
    defaults: { _controller: "TipddyMasleadsBundle:Organizacion:new" }

company_create:
    pattern:  /create
    defaults: { _controller: "TipddyMasleadsBundle:Organizacion:create" }
    requirements: { _method: post }

company_edit:
    pattern:  /{id}/edit/{page}
    defaults: { _controller: "TipddyMasleadsBundle:Organizacion:edit", page: 1 }
    requirements:
       page: \d+

company_update:
    pattern:  /{id}/update/{page}
    defaults: { _controller: "TipddyMasleadsBundle:Organizacion:update", page: 1 }
    requirements:
       _method: post
       page: \d+

company_delete:
    pattern:  /{id}/delete
    defaults: { _controller: "TipddyMasleadsBundle:Organizacion:delete" }
    requirements: { _method: post }

  