user:
    pattern: /{page}
    defaults: { _controller:"TipddyMasleadsBundle:Usuario:index", page: 1}
    requirements:
       page: \d+
  
user_ver:
    pattern:  /{id}/ver
    defaults: { _controller: "TipddyMasleadsBundle:Usuario:ver" }

user_nuevo:
    pattern:  /nuevo
    defaults: { _controller: "TipddyMasleadsBundle:Usuario:nuevo" }

user_crear:
    pattern:  /crear
    defaults: { _controller: "TipddyMasleadsBundle:Usuario:crear" }
    requirements: { _method: post }

user_editar:
    pattern:  /{id}/editar/{page}
    defaults: { _controller: "TipddyMasleadsBundle:Usuario:editar", page:1 }

user_actualizar:
    pattern:  /{id}/actualizar
    defaults: { _controller: "TipddyMasleadsBundle:Usuario:actualizar" }
    requirements: { _method: post }

user_borrar:
    pattern:  /{id}/borrar
    defaults: { _controller: "TipddyMasleadsBundle:Usuario:borrar" }
    requirements: { _method: post }
