user:
    pattern: /{page}
    defaults: { _controller:"TipddyMasleadsBundle:Usuario:index", page: 1}
    requirements:
       page: \d+
  
user_show:
    pattern:  /{id}/show/{page}
    defaults: { _controller: "TipddyMasleadsBundle:Usuario:show", page: 1 }
    requirements:
        id: \d+
        page: \d+
  
user_new:
    pattern:  /new
    defaults: { _controller: "TipddyMasleadsBundle:Usuario:new" }

user_create:
    pattern:  /create
    defaults: { _controller: "TipddyMasleadsBundle:Usuario:create" }
    requirements: { _method: post }

user_edit:
    pattern:  /{id}/edit/{page}
    defaults: { _controller: "TipddyMasleadsBundle:Usuario:edit", page:1 }
    requirements:
        id: \d+
        page: \d+

user_update:
    pattern:  /{id}/update/{page}
    defaults: { _controller: "TipddyMasleadsBundle:Usuario:update", page: 1 }
    requirements:
         _method: post
         id: \d+
         page: \d+
         
user_delete:
    pattern:  /{id}/delete/{page}
    defaults: { _controller: "TipddyMasleadsBundle:Usuario:delete", page: 1 }
    requirements:
        _method: get
        id: \d+
        page: \d+ 
