user:
    pattern: /{page}
    defaults: { _controller:"TipddyMasleadsBundle:Usuario:index", page: 1}
    requirements:
       page: \d+
  
user_show:
    pattern:  /{id}/show
    defaults: { _controller: "TipddyMasleadsBundle:Usuario:show" }

user_new:
    pattern:  /new
    defaults: { _controller: "TipddyMasleadsBundle:Usuario:new" }

user_create:
    pattern:  /create
    defaults: { _controller: "TipddyMasleadsBundle:Usuario:create" }
    requirements: { _method: post }

user_edit:
    pattern:  /{id}/edit/{page}
    defaults: { _controller: "TipddyMasleadsBundle:Usuario:edit", page:1 }

user_update:
    pattern:  /{id}/update
    defaults: { _controller: "TipddyMasleadsBundle:Usuario:update" }
    requirements: { _method: post }

user_delete:
    pattern:  /{id}/delete
    defaults: { _controller: "TipddyMasleadsBundle:Usuario:delete" }
    requirements: { _method: post }
